name: Build + Deploy website

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.92.2'
          extended: true

      - name: Build Website
        run: hugo --minify

      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@5.2
        # only for main branch
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          switches: -avzr --delete
          path: public/
          remote_path: ${{ secrets.WEBSITE_DEPLOY_PATH }}
          remote_host: ${{ secrets.WEBSITE_DEPLOY_HOST }}
          remote_port: ${{ secrets.WEBSITE_DEPLOY_PORT }}
          remote_user: ${{ secrets.WEBSITE_DEPLOY_USER }}
          remote_key:  ${{ secrets.WEBSITE_DEPLOY_KEY }}
